description: Ubuntu 14.04 Desktop version contains all development tools needed for play 2.2.3, sbt 0.13.5 and nodejs ready to use.
hint: The oracle jdk 8 installation is full automated and accept the license automated. To use npm perform su -l vagrant on the terminal. Maybe restart needed because new profile.d scripts will be added they take effect after restart.
username: vagrant
password: vagrant
